# Generated by Django 5.0.4 on 2024-04-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_commentaire_reponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='lesson',
            new_name='nom_lesson',
        ),
    ]
