# Generated by Django 5.0.4 on 2024-05-13 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0004_quiz_remove_lesson_matiere_remove_lesson_niveau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='programmes.lesson'),
        ),
    ]
