# Generated by Django 5.0.4 on 2024-04-07 16:26

import django.db.models.deletion
import utilisateurs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=150)),
                ('photo_profile', models.ImageField(upload_to=utilisateurs.models.renomer_image)),
                ('type_profil', models.CharField(choices=[('etudiant', 'Étudiant'), ('enseignant', 'Enseignant'), ('parent', 'Parent')], default='etudiant', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
